ALTER TYPE "StatusEnum" ADD VALUE IF NOT EXISTS 'PENDING_CLOSURE';

ALTER TABLE "Profile"
ADD COLUMN IF NOT EXISTS "city" TEXT,
ADD COLUMN IF NOT EXISTS "country" TEXT,
ADD COLUMN IF NOT EXISTS "id_number" TEXT,
ADD COLUMN IF NOT EXISTS "postal_code" TEXT;

-- Decimal conversions
ALTER TABLE "Transaction"
ALTER COLUMN "amount" TYPE DECIMAL(19,2);

ALTER TABLE "User"
ALTER COLUMN "walletBalance" TYPE DECIMAL(19,2),
ALTER COLUMN "totalEarnings" TYPE DECIMAL(19,2);

ALTER TABLE "Earnings"
ALTER COLUMN "amount" TYPE DECIMAL(19,2);

ALTER TABLE "WalletTransaction"
ALTER COLUMN "amount" TYPE DECIMAL(19,2);