export enum EmailType {
    WELCOME = "WELCOME",
    PASSWORD_RESET = "PASSWORD_RESET",
    VERIFY_EMAIL = "VERIFY_EMAIL",
    TRANSACTION_PENDING_CLOSURE_INITIATOR = "TRANSACTION_PENDING_CLOSURE_INITIATOR",
    TRANSACTION_PENDING_CLOSURE_COUNTERPARTY = "TRANSACTION_PENDING_CLOSURE_COUNTERPARTY",
    TRANSACTION_COMPLETED = "TRANSACTION_COMPLETED",
    TRANSACTION_DISPUTED = "TRANSACTION_DISPUTED",
}